### ISSUE TITLE
PS button not working

### ISSUE THREAD

**Issue by sergiodebst** [nefarius/Shibari#12] opened 2020-11-03 13:14 UTC
Hello, since I've not seen no one asking for this, I don't know if this is occurring only to me or no one cares about the PS button.

If I use the XBOX sink this is how it looks my controller:
Only 10 buttons, the button 11 would be the PS since L2 and R2 is the Z axis
![imagen](https://user-images.githubusercontent.com/5172886/97985888-2e7d3b80-1dd9-11eb-88a4-edcf526de685.png)

And using the DS4 sink:
I have four more buttons, where two of them are L2 and R2 that now they have a button in addition to de rotation X and rotation Y, and the 13 and 14 buttons that don't know what they are since nothing in my controller activates them.
![imagen](https://user-images.githubusercontent.com/5172886/97987838-3db1b880-1ddc-11eb-8ea1-a8f21848106a.png)

I have not seen your entire code but I noticed that in XBOX sink you are pairing PS button with Guide button
https://github.com/ViGEm/Shibari/blob/402d484f4f2f8350b24ad942de66ba75f1da173a/Sinks/Shibari.Sub.Sink.ViGEm.X360/Core/ViGEmSinkX360.cs#L36-L53

But in DS4 sink you are not pairing PS button
https://github.com/ViGEm/Shibari/blob/402d484f4f2f8350b24ad942de66ba75f1da173a/Sinks/Shibari.Sub.Sink.ViGEm.DS4/Core/ViGEmSinkDS4.cs#L32-L46

For me, the PS button is not working in any of the sinks.

I tested it with two controllers:
- Original Sony Sixaxis controller
- Non original PS3 controller

Using Shibari both are working in the same way (with no PS button), without ViGEm and Fireshock there is a little diference both get recognized by windows but in the properties of the game device the only one showing what I press on the controller is the non original PS3 controller.

**Comment by nefarius** [comment] 2020-11-03 13:48
Hello!

The Guide button is not mapped/exposed to the virtual HID device so that's expected behaviour, since Windows can catch the Guide button and toggle the Overlay (Game bar?) with it, or Steam can hook it to enable Big Picture mode.

For the DS4, good catch, I didn't even notice it not mapping, should be added 😅 

Cheers

**Comment by sergiodebst** [comment] 2020-11-03 14:34
**EDIT:** Ok, I builded Shibari and adding the missing mapping in DS4 sink, and seems that it make the PS button to work, so sorry for my own non sense extra worries in this message.
- - - - - - - 

> The Guide button is not mapped/exposed to the virtual HID device so that's expected behaviour, since Windows can catch the Guide button and toggle the Overlay (Game bar?) with it, or Steam can hook it to enable Big Picture mode.

I am not sure what you are saying, Steam handles PS button correctly even if windows does not? (I don't play games throught Steam so I didn't test it).

Anyway, I wanted the PS button to be working/handled/mapped (not sure about how to say it :sweat_smile:) because I want to use it in AutoHotKeys to start an action (NVIDIA video Recording(Alt+F9) in this case).

I tried [XOutput](https://github.com/csutorasa/XOutput) and that software keep the PS button "usable", and as it requieres ViGEm I thought that with Shibari maybe could be any approach to make the PS button work. I will use Shibari instead of XOutput even if it is not possible but, is there a way to make the PS button work even if I have to code something? (I can code if there's no need to dig much in concepts like HID and driver programming)

**Comment by sergiodebst** [comment] 2020-11-03 14:51
Do I close this issue myself? Or will you close it when you add the DS4 sink mapping in your code?

**Comment by nefarius** [comment] 2020-11-03 17:49
> **EDIT:** Ok, I builded Shibari and adding the missing mapping in DS4 sink, and seems that it make the PS button to work, so sorry for my own non sense extra worries in this message.

No need to apologize, glad you figured it out 😁 

> I am not sure what you are saying, Steam handles PS button correctly even if windows does not? (I don't play games throught Steam so I didn't test it).

Every Xbox 360 Controller implicitly emulates a virtual HID device (the one you actually see in the Joystick test dialog) and the PS/Guide button is not mapped to that, that is by design.

> I tried [XOutput](https://github.com/csutorasa/XOutput) and that software keep the PS button "usable", and as it requieres ViGEm I thought that with Shibari maybe could be any approach to make the PS button work. I will use Shibari instead of XOutput even if it is not possible but, is there a way to make the PS button work even if I have to code something? (I can code if there's no need to dig much in concepts like HID and driver programming)

Currently only Shibari is able to "understand" the devices running the FireShock driver, that's why XOutput can't offer the same. This will change soon though as I have a Shibari successor in the works.

I'll close the issue. Cheers.

**Closed as completed by nefarius** 2020-11-03 17:49 UTC

**Comment by sergiodebst** [comment] 2020-11-03 21:09
Thanks for your clarifications and your work, I really appreciate it. 😀

**Comment by ledufff** [comment] 2021-03-04 18:42
Hello @sergiodebst,  could you please detail a bit more how did you built Shibari to map your PS button?

**Comment by sergiodebst** [comment] 2021-03-04 23:10
Well I just added a new line en the previously mentioned code with the missing mapping:
```
{DualShock3Buttons.Ps, DualShock4SpecialButton.Ps}
```

And about the building proccess, I did it with Visual Studio without problems.

Additionally, if anyone is interested I also builded a second dll changing the mapping of the `Select` button in order to act as the `Touchpad` button because could be some games that use the Touchpad button and does not allow you to remap it to another button, so I repaced the first mapping in this way
```
{DualShock3Buttons.Select, DualShock4SpecialButton.Touchpad},
```

Then I placed both dll in Sinks folder with this names `Shibari.Sub.Sink.ViGEm.DS4.dll_normal` and `Shibari.Sub.Sink.ViGEm.DS4.dll_touchpad`

Created two `.bat` files to choose with wich configuration I want to play
```
copy /Y "Sinks\Shibari.Sub.Sink.ViGEm.DS4.dll_normal" "Sinks\Shibari.Sub.Sink.ViGEm.DS4.dll"
Shibari.Dom.Server.exe
```
```
copy /Y "Sinks\Shibari.Sub.Sink.ViGEm.DS4.dll_touchpad" "Sinks\Shibari.Sub.Sink.ViGEm.DS4.dll"
Shibari.Dom.Server.exe
```
And finally create shortcust for the bat files and configure icons, etc...

**Comment by ledufff** [comment] 2021-03-05 00:24
Thank you buddy.
